FROM elixir:1.18-otp-27-alpine

RUN apk add --no-cache git build-base

WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && mix local.rebar --force

# Cache deps
COPY mix.exs mix.lock* ./
RUN mix deps.get

COPY . .
